
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testing

  backend:
    depends_on:
      - mongodb
    image: ${DOCKER_USERNAME}/express-backend:${TAG:-latest}  # Pre-built image from DockerHub
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/testing  # Uses Docker's internal network
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/react-frontend:${TAG:-latest}  # Pre-built image from DockerHub
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data: